name: wisp_app
description: Mobile interface for the WISP neonatal monitor.
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.31.0 # Plugin to talk to the WISP sensor
  google_fonts: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
